language: nix
install:
  - nix-channel --update
  - ./scripts/install-dapphub-cache.sh
  - nix-env -if https://github.com/cachix/cachix/tarball/master --substituters https://cachix.cachix.org --trusted-public-keys cachix.cachix.org-1:eWNHQldwUO7G2VkjpnjDbWwy4KQ/HNxht7H4SSoMckM=
  - cachix authtoken ${CACHIX_AUTHTOKEN}
  - cachix use dapp
script: nix-build release.nix -A dapphub.linux.stable | cachix push dapp
