version: 2
jobs:
  build:
    docker:
      - image: nixos/nix:2.0
    steps:
      - run: nix-channel --update
      - run: nix-env -iA bash git -f '<nixpkgs>'
      - checkout
      - run: git submodule sync
      - run: git submodule update --init
      # - run: ./bump
      - run:
          name: configure dapphub binary cache
          command: |
            mkdir /etc/nix
            cat <<EOF >> /etc/nix/nix.conf
            binary-caches = https://cache.nixos.org https://d121dybo9yhl5h.cloudfront.net
            trusted-binary-caches = https://cache.nixos.org https://d121dybo9yhl5h.cloudfront.net
            trusted-public-keys = cache.nixos.org-1:6NCHdD59X431o0gWypbMrAURkbJ16ZPMQFGspcDShjY= d121dybo9yhl5h.cloudfront.net-1:IOpHdUBT2b3fIRb/TBm+V8Y8eEj52fStcllzD6TFYyU=
            EOF
      - run: nix-build release.nix -A dapphub.linux.stable
