version: 2
jobs:
  build:
    docker:
      - image: nixos/nix:2.0
    steps:
      - run: nix-channel --update
      - run: nix-env -iA git -f '<nixpkgs>'
      - checkout
      - run: git submodule sync
      - run: git submodule update --init
      - run: ./bump
